services:
  aura:
    build: ./aura-simple
    container_name: aura_mega
    restart: unless-stopped
    privileged: true
    environment:
      - EXPORTER_PORT=8080
      - COLLECTION_INTERVAL=15
    ports:
      - "8080:8080"   # Web UI + Metrics + API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    labels:
      - "project=aura"
      - "component=mega-monitoring"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]