services:
  cuda-test:
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    container_name: cuda_test_workload
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: sleep infinity
    labels:
      - "project=gpu-test"
    restart: unless-stopped
    
  ollama-fixed:
    image: ollama/ollama:0.3.12
    container_name: ollama_with_gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"
    labels:
      - "project=gpu-test"
    restart: unless-stopped

volumes:
  ollama_data: