version: '3.8'

services:
  # Test containers for "webapp" project group
  webapp-frontend:
    image: nginx:alpine
    container_name: test_webapp_frontend
    ports:
      - "8081:80"
    labels:
      - "project=webapp"
    networks:
      - benchmarking_mon_network
    restart: unless-stopped

  webapp-api:
    image: httpd:alpine
    container_name: test_webapp_api
    ports:
      - "8082:80"
    labels:
      - "project=webapp"
    networks:
      - benchmarking_mon_network
    restart: unless-stopped

  # Test containers for "database" project group
  db-primary:
    image: redis:alpine
    container_name: test_db_primary
    ports:
      - "6379:6379"
    labels:
      - "project=database"
    networks:
      - benchmarking_mon_network
    restart: unless-stopped

  db-cache:
    image: memcached:alpine
    container_name: test_db_cache
    ports:
      - "11211:11211"
    labels:
      - "project=database"
    networks:
      - benchmarking_mon_network
    restart: unless-stopped

  # Test container for "ml" project group  
  ml-processor:
    image: alpine:latest
    container_name: test_ml_processor
    labels:
      - "project=ml"
    networks:
      - benchmarking_mon_network
    restart: unless-stopped
    command: sh -c "while true; do echo 'ML processing...'; sleep 30; done"

networks:
  benchmarking_mon_network:
    external: true