process_names:
  - name: "{{.Comm}}"
    cmdline:
    - '.+'

  - name: "docker"
    cmdline:
    - 'docker'

  - name: "prometheus"
    cmdline:
    - 'prometheus'

  - name: "grafana"
    cmdline:
    - 'grafana'

  - name: "node_exporter"
    cmdline:
    - 'node_exporter'

  - name: "cadvisor"
    cmdline:
    - 'cadvisor'

  - name: "systemd"
    cmdline:
    - 'systemd'

  - name: "ssh"
    cmdline:
    - 'sshd'

  - name: "nginx"
    cmdline:
    - 'nginx'

  - name: "apache"
    cmdline:
    - 'apache'

  - name: "mysql"
    cmdline:
    - 'mysql'

  - name: "postgres"
    cmdline:
    - 'postgres'