global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm_exporter:9400']

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process_exporter:9256']

  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['custom_metrics:9100']

  - job_name: 'blackbox'
    static_configs:
      - targets: ['blackbox_exporter:9115']

  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama_exporter:9200']
        labels:
          component: 'ollama'
          gpu_workload: 'llm'

  - job_name: 'gpu-inference'
    static_configs:
      - targets: ['gpu_inference_exporter:9201']
        labels:
          component: 'gpu-inference'
          method: 'memory-delta'

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://prometheus:9090
        - http://grafana:3000
        - http://cadvisor:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

